language: java

# -------------  ALL BRANCHES FIRE MVN INSTALL  ------------- ------------- --------
# DEVELOP: BUILD ON COMMIT (NO DEPLOY)
# MASTER: BUILD ON COMMIT (NO DEPLOY)
# +++++++++++++  STABLE AND TAGS FIRE DEPLOY    ++++++++++++++++++++++++++++++++++++
# STABLE: BUILD ON COMMIT + DEPLOY SNAPSHOT RELEASE
# TAGS: BUILD ON COMMIT + DEPLOY SONATYPE VERSION  RELEASE
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Be aware when adding 'branch.only' they can exclude tags deployment is not fired
# -------------------------- ------------- ------------- ------------- ------------- 


matrix:
  include:
    - os: linux
      dist: xenial
      jdk: openjdk11
                  
cache:
    directories:
    - $HOME/.m2/repository


script:
  - echo PATH = ${PATH}
  - echo $JAVA_HOME
  - java -version


before_install:
    - export GPG_TTY=/dev/pts/4
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
    - docker version
    - docker info
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
    - echo $project_version


install: 
    mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true  -B -V


deploy: 
# 1. Trigger a snapshot deploy when commit a stable version
    - provider: script
      script: bash .travis/snapshot.sh 
      skip_cleanup: true
      on:
        branch: stable


# 1. Trigger a version deploy when a commit on tag
    - provider: script
      script: bash .travis/release.sh 
      skip_cleanup: true
      on:
        tags: true
        all_branches: true
