version: '3.7'
services:

  soagg-database:
    image: jsoagger/soagg-h2:latest
    restart: on-failure
    ports:
      - 1521:1521
      - 81:81
    
    volumes:
       - ./_docker-compose/data/:/opt/h2-data
      
    environment:
      - DB_USER=sa
      - DB_PASSWORD=
    
    networks:
      - the_soagg_network  
      
                
  soagg-foundation-srv:
    image: helloworld/starter-foundation-srv:1.0.0-SNAPSHOT
    restart: on-failure
    ports:
      - 8080:8080
    
    volumes:
      - ./_docker-compose/server:/spring-config/:ro
      
    depends_on:
      - soagg-database
          
    networks:
      - the_soagg_network


  soagg-webdev:
    image: helloworld/starter-web-reactapp:1.0.0-SNAPSHOT
    ports:
      - '3000:3000'
      
    environment:
      - JSOAGGER_API_URL=http://localhost:8080/jsoagger
      - NODE_ENV=dev
      - CHOKIDAR_USEPOLLING=true
           
    networks:
      - the_soagg_network  
                 
networks:
  the_soagg_network:
    driver: "bridge"  
  